# Generated by Django 4.2.9 on 2026-04-14 08:35

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the chat entry', primary_key=True, serialize=False)),
                ('question', models.TextField(help_text="The user's question")),
                ('answer', models.TextField(help_text='The generated answer')),
                ('context_used', models.JSONField(default=list, help_text='List of context chunks used for answering')),
                ('sources', models.JSONField(default=list, help_text='List of source documents/databases referenced')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the interaction occurred')),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken to generate response (seconds)', null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Approximate tokens used in LLM call', null=True)),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title or name of the document', max_length=255)),
                ('file', models.FileField(help_text='The uploaded document file', upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt'])])),
                ('file_type', models.CharField(help_text='File extension (pdf, txt, etc.)', max_length=10)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of upload')),
                ('processed', models.BooleanField(default=False, help_text='Whether the document has been processed and indexed')),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of text chunks extracted from this document')),
                ('faiss_index_id', models.CharField(blank=True, help_text="Identifier for the FAISS index containing this document's embeddings", max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JSONDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the JSON database', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the JSON database', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the database contents', null=True)),
                ('data', models.JSONField(help_text='The JSON data to be indexed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('record_count', models.IntegerField(default=0, help_text='Number of records in the JSON data')),
                ('processed', models.BooleanField(default=False, help_text='Whether the data has been processed and indexed')),
                ('faiss_index_id', models.CharField(blank=True, help_text="Identifier for the FAISS index containing this database's embeddings", max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'JSON Database',
                'verbose_name_plural': 'JSON Databases',
                'ordering': ['-created_at'],
            },
        ),
    ]
